WarsawEventsMVC/Models/ApplicationUser.cs
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using WarsawEventsMVC.Models.Entities;
using System.Collections.Generic;

namespace WarsawEventsMVC.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual ICollection<Invitation> SendInvitations { get; set; }
        public virtual ICollection<Invitation> ReceiveInvitations { get; set; }

        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            // Add custom user claims here
            return userIdentity;
        }
    }
}

WarsawEventsMVC/Models/Entities/Place.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WarsawEventsMVC.Models.Entities
{
    public class Place: Entity
    {
        [Display(Name = "Nazwa miejsca")]
        [Required(ErrorMessage = "Podaj nazwe miejsca")]
        [StringLength(30)]
        public string PlaceName { get; set; }

        [Display(Name = "Ulica")]
        [Required(ErrorMessage = "Podaj nazwe ulicy")]
        [StringLength(30)]
        public string StreetName { get; set; }

        [Display(Name = "Numer domu")]
        [Required(ErrorMessage = "Podaj numer domu")]
        public int Streetnumber { get; set; }

        [Display(Name = "Ocena")]
        [ScaffoldColumn(false)]
        public double Average { get; set; }

        //Foreign key for District
        public int DistrictId { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}

WarsawEventsMVC/Controllers/ApplicationUsersController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WarsawEventsMVC.Models;
using WarsawEventsMVC.Models.Entities;

namespace WarsawEventsMVC.Controllers
{
    public class ApplicationUsersController : Controller
    {
        private WarsawEventsContext db = new WarsawEventsContext();

        // GET: ApplicationUsers
        IRepository<ApplicationUser> repUser;
        IRepository<Invitation> repInvitation;
        public ApplicationUsersController(IRepository<ApplicationUser> repUser, IRepository<Invitation> repInvitation)
        {
            this.repUser = repUser;
            this.repInvitation = repInvitation;
        }

        public ActionResult Index(string filter)
        {
           
            ViewBag.TypeOfUsers = filter;
            string id = "";
            if (User != null && User.Identity.GetUserId() != null)
            {
                id = User.Identity.GetUserId();
            }

            return View(repUser.GetAll().Where(u => u.Id != id));
        }

        public ActionResult UpdateUsers(string filter)
        {
            ViewBag.TypeOfUsers = filter;
            List<string> users = null;
            string id = "";
            if (User.Identity.GetUserId() != null)
            {
                 id = User.Identity.GetUserId();
                ApplicationUser user = repUser.Get().Where(u => u.Id == id)
                    .Include(u => u.SendInvitations).Include(u => u.ReceiveInvitations).FirstOrDefault();
                users = FilterUsersTool.GetUserList(filter, user);
            }

           

            IEnumerable<ApplicationUser> entity;

            if (users == null)
            {
                entity = repUser.GetAll().Where(u => u.Id != id) ;
            }
            else
            {
                entity = repUser.Get().Where(u => users.Contains(u.Id) && u.Id != id).ToList();
            }
            return PartialView("_ApplicationUsers", entity);
        }

        // GET: ApplicationUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = repUser.Find(Int32.Parse(id));
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApplicationUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                repUser.Insert(applicationUser);
                repUser.Save();
                return RedirectToAction("Index");
            }

            return View(applicationUser);
        }

        public ActionResult Accept(string id)
        {
            string RecId = User.Identity.GetUserId();
            Invitation inv = repInvitation.Get().Where(i => i.SendUserId == id && i.ReceiveUserId == RecId).FirstOrDefault();
            if(inv != null)
            {
                ViewBag.Message = "Zaakceptowano zaproszenie.";
                inv.IsAccepted = true;
                repInvitation.Update(inv);
                repInvitation.Save();
            }
            string Id = "";
            if (User.Identity.GetUserId() != null)
            {
                Id = User.Identity.GetUserId();
            }

            return View("~/Views/ApplicationUsers/Index.cshtml", repUser.GetAll().Where(u => u.Id != Id)) ;
        }
        public ActionResult Invite(string id)
        {
            string Id = "";
            if (User.Identity.GetUserId() != null)
            {
                Id = User.Identity.GetUserId();
            }

            string SendId = User.Identity.GetUserId();
            Invitation old = repInvitation.Get().Where(i => i.SendUserId == SendId && i.ReceiveUserId == id).FirstOrDefault();
            if (old != null)
            {
                ViewBag.Message = "Już wcześniej wysłano zaproszenie.";
                return View("~/Views/ApplicationUsers/Index.cshtml", repUser.GetAll().Where(u => u.Id != Id) );
            }//throw new HttpResponseException(HttpStatusCode.Forbidden);////return Request.CreateResponse(HttpStatusCode.Forbidden);
            Invitation recInv = repInvitation.Get().Where(i => i.SendUserId == id && i.ReceiveUserId == SendId).FirstOrDefault();
            if(recInv != null)
            {
                if (recInv.IsAccepted == true)
                {
                    ViewBag.Message = "Jesteście już znajomymi.";
                }
                else
                {
                    recInv.IsAccepted = true;
                    repInvitation.Update(recInv);
                    repInvitation.Save();
                    ViewBag.Message = "Użytkownik, którego chcesz zaprosić wysłał Ci już zaproszenie, więc zostaliście znajomymi";
                }
                return View("~/Views/ApplicationUsers/Index.cshtml", repUser.GetAll().Where(u => u.Id != Id));
            }
            repInvitation.Insert(new Invitation() { SendUserId = SendId, ReceiveUserId = id, IsAccepted = false });
            repInvitation.Save();

            ViewBag.Message = "Wysłano zaproszenie.";

            return View("~/Views/ApplicationUsers/Index.cshtml",repUser.GetAll().Where(u => u.Id != Id));

        }

        // GET: ApplicationUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = repUser.Find(Int32.Parse(id));
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(applicationUser);
        }

        // GET: ApplicationUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser applicationUser = repUser.Find(Int32.Parse(id));
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: ApplicationUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ApplicationUser applicationUser = repUser.Find(Int32.Parse(id));
            repUser.Delete(Int32.Parse(applicationUser.Id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WarsawEventsMVC/Controllers/PlacesController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WarsawEventsMVC.Models;
using WarsawEventsMVC.Models.Entities;

namespace WarsawEventsMVC.Controllers
{
    public class PlacesController : Controller
    {
        private WarsawEventsContext db = new WarsawEventsContext();

        IRepository<Place> repPlace;
        IRepository<Grade> repGrade;

        public PlacesController(IRepository<Place> repPlace, IRepository<Grade> repGrade)
        {
            
            this.repPlace = repPlace;
            this.repGrade = repGrade;
        }

        // GET: Places
        public ActionResult Index(int? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);


            var places = repPlace.Get().Include(p => p.District).OrderBy(p=>p.PlaceName);
            //places.ForEach(p => p.Average = 0);
            //places.ForEach(p => repPlace.Update(p));
            //repPlace.Save();
            return View(places.ToPagedList(pageNumber,pageSize));
        }


        [HttpPost]
        [Authorize]
        public ActionResult UpdateAverage(int rate, int placeId, int? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            string userId = User.Identity.GetUserId();
            Grade old = repGrade.Get().Where(g => g.PlaceId == placeId && g.ApplicationUserId == userId).FirstOrDefault();
            if (old != null) //uzytkownik ocenil juz to miejsce
            {
                ViewBag.Message = "Oceniłeś już to miejsce";
                return PartialView("_Places", repPlace.Get().Include(p => p.District).OrderBy(p => p.PlaceName).ToPagedList(pageNumber, pageSize));
            }
            repGrade.Insert(new Grade() { ApplicationUserId = userId, Value = rate, PlaceId = placeId });
            repGrade.Save();
            Place place = repPlace.Get().Where(p => p.Id == placeId).Include(p => p.Grades).FirstOrDefault();
            UpdatePlaceAverage(place);
            var places = repPlace.Get().Include(p => p.District).OrderBy(p => p.PlaceName).ToPagedList(pageNumber, pageSize);
            return PartialView("_Places", places);
        }

        private void UpdatePlaceAverage(Place place)
        {

            int sum = 0;
            foreach (var g in place.Grades)
            {
                sum += g.Value;
            }
            place.Average = (double)sum / place.Grades.Count;
            repPlace.Update(place);
            repPlace.Save();
        }

        // GET: Places/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // GET: Places/Create
        public ActionResult Create()
        {
            ViewBag.DistrictId = new SelectList(db.Districts, "Id", "DistrictName");
            return View();
        }

        // POST: Places/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PlaceName,StreetName,Streetnumber,Average,DistrictId")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Places.Add(place);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DistrictId = new SelectList(db.Districts, "Id", "DistrictName", place.DistrictId);
            return View(place);
        }

        // GET: Places/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            ViewBag.DistrictId = new SelectList(db.Districts, "Id", "DistrictName", place.DistrictId);
            return View(place);
        }

        // POST: Places/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PlaceName,StreetName,Streetnumber,Average,DistrictId")] Place place)
        {
            if (ModelState.IsValid)
            {
                db.Entry(place).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DistrictId = new SelectList(db.Districts, "Id", "DistrictName", place.DistrictId);
            return View(place);
        }

        // GET: Places/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Place place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        // POST: Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Place place = db.Places.Find(id);
            db.Places.Remove(place);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WarsawEventsMVC/Views/Shared/_ApplicationUsers.cshtml
@model IEnumerable<WarsawEventsMVC.Models.ApplicationUser>
<table class="table">
    <tr>
        @*<th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailConfirmed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PasswordHash)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecurityStamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TwoFactorEnabled)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LockoutEnabled)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccessFailedCount)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailConfirmed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PasswordHash)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SecurityStamp)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumberConfirmed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TwoFactorEnabled)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LockoutEndDateUtc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LockoutEnabled)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccessFailedCount)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |*@
              @if (ViewBag.TypeOfUsers == null || ViewBag.TypeOfUsers == "Wszyscy")
              {
                    @Html.ActionLink("Zaproś", "Invite", new { id = item.Id }) 
              }
              @if (ViewBag.TypeOfUsers == "Zapraszający")
              {
                    @Html.ActionLink("Zaakceptuj", "Accept", new { id = item.Id })
              }

            </td>
        </tr>
    }

</table>


WarsawEventsMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Warsaw Events", "Index", "Events", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                    <li>@Html.ActionLink("Pokaż Użytkowników", "Index", "ApplicationUsers")</li>
                    <li>@Html.ActionLink("Pokaż Miejsca", "Index", "Places")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-full body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

WarsawEventsMVC/Views/Shared/_Places.cshtml
@model PagedList.IPagedList<WarsawEventsMVC.Models.Entities.Place>
@using PagedList.Mvc;
@{ 
    
   
    <div id='okienko' style='position: absolute; z-index: 2; top: 100px; width: 400px; height: 200px;  padding-top: 40px; text-align: center; color: black; box-shadow: 3px 3px 5px; display: none; background-color: white; border: 1px solid black;'>
        <span id='tresc' style="font-size: 18px;"> </span>
        <button id='button_zamknij' style='position: absolute; bottom: 10px; right: 10px;'>zamknij</button>
    </div>


 
    if (ViewBag.Message != null)
    {
        <script>
            var szerokosc_okna = parseInt(document.getElementById('okienko').style.width);
            var szerokosc_strony = document.body.clientWidth;
            var left = (szerokosc_strony / 2) - (szerokosc_okna / 2);
            document.getElementById('okienko').style.left = left + 'px';
            document.getElementById('tresc').innerHTML = '@ViewBag.Message';
            document.getElementById('okienko').style.display = 'block';
            document.getElementById('button_zamknij').onclick = function () {
                document.getElementById('okienko').style.display = 'none';
            }
        </script>
     }
  }

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().PlaceName)
        </th>
        <th>
            @Html.DisplayName("Dzielnica")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Average)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().StreetName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Streetnumber)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlaceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.District.DistrictName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Average)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StreetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Streetnumber)
            </td>
            <td>
                @using (Ajax.BeginForm("UpdateAverage", new { placeId = item.Id, page = Model.PageNumber }, new AjaxOptions()
                {
                    UpdateTargetId = "places",
                    InsertionMode = InsertionMode.Replace,
                    HttpMethod = "Post"
                }))
                {
                    <div class="col-md-5">
                        @Html.DropDownList("Rate", new List<SelectListItem>()
                    {
                         new SelectListItem {Text="1",Value="1" },
                         new SelectListItem {Text="2",Value="2" },
                         new SelectListItem {Text="3",Value="3" },
                         new SelectListItem {Text="4",Value="4" },
                         new SelectListItem {Text="5",Value="5" }
                    }, new { @class = "col-md-2 form-control" })

                    </div>
                    <input type="submit" class="btn btn-primary" value="Oceń" />

                }
            </td>







        </tr>
    }

</table>

    Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
new
{
    page
}))